// This file is part of GoRE.
//
// Copyright (C) 2019-2023 GoRE Authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// Code generated by go generate; DO NOT EDIT.

package gore

type moduledata2064 struct {
	PcHeader                                    uint64
	Funcnametab, Funcnametablen, Funcnametabcap uint64
	Cutab, Cutablen, Cutabcap                   uint64
	Filetab, Filetablen, Filetabcap             uint64
	Pctab, Pctablen, Pctabcap                   uint64
	Pclntable, Pclntablelen, Pclntablecap       uint64
	Ftab, Ftablen, Ftabcap                      uint64
	Findfunctab                                 uint64
	Minpc                                       uint64
	Maxpc                                       uint64
	Text                                        uint64
	Etext                                       uint64
	Noptrdata                                   uint64
	Enoptrdata                                  uint64
	Data                                        uint64
	Edata                                       uint64
	Bss                                         uint64
	Ebss                                        uint64
	Noptrbss                                    uint64
	Enoptrbss                                   uint64
	Covctrs                                     uint64
	Ecovctrs                                    uint64
	End                                         uint64
	Gcdata                                      uint64
	Gcbss                                       uint64
	Types                                       uint64
	Etypes                                      uint64
	Rodata                                      uint64
	Gofunc                                      uint64
	Textsectmap, Textsectmaplen, Textsectmapcap uint64
	Typelinks, Typelinkslen, Typelinkscap       uint64
	Itablinks, Itablinkslen, Itablinkscap       uint64
}

func (md moduledata2064) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypesAddr:     md.Types,
		TypesLen:      md.Etypes - md.Types,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		ITabLinkAddr:  md.Itablinks,
		ITabLinkLen:   md.Itablinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
		GoFuncVal:     md.Gofunc,
	}
}

type moduledata2032 struct {
	PcHeader                                    uint32
	Funcnametab, Funcnametablen, Funcnametabcap uint32
	Cutab, Cutablen, Cutabcap                   uint32
	Filetab, Filetablen, Filetabcap             uint32
	Pctab, Pctablen, Pctabcap                   uint32
	Pclntable, Pclntablelen, Pclntablecap       uint32
	Ftab, Ftablen, Ftabcap                      uint32
	Findfunctab                                 uint32
	Minpc                                       uint32
	Maxpc                                       uint32
	Text                                        uint32
	Etext                                       uint32
	Noptrdata                                   uint32
	Enoptrdata                                  uint32
	Data                                        uint32
	Edata                                       uint32
	Bss                                         uint32
	Ebss                                        uint32
	Noptrbss                                    uint32
	Enoptrbss                                   uint32
	Covctrs                                     uint32
	Ecovctrs                                    uint32
	End                                         uint32
	Gcdata                                      uint32
	Gcbss                                       uint32
	Types                                       uint32
	Etypes                                      uint32
	Rodata                                      uint32
	Gofunc                                      uint32
	Textsectmap, Textsectmaplen, Textsectmapcap uint32
	Typelinks, Typelinkslen, Typelinkscap       uint32
	Itablinks, Itablinkslen, Itablinkscap       uint32
}

func (md moduledata2032) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypesAddr:     uint64(md.Types),
		TypesLen:      uint64(md.Etypes - md.Types),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		ITabLinkAddr:  uint64(md.Itablinks),
		ITabLinkLen:   uint64(md.Itablinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
		GoFuncVal:     uint64(md.Gofunc),
	}
}

type moduledata1864 struct {
	PcHeader                                    uint64
	Funcnametab, Funcnametablen, Funcnametabcap uint64
	Cutab, Cutablen, Cutabcap                   uint64
	Filetab, Filetablen, Filetabcap             uint64
	Pctab, Pctablen, Pctabcap                   uint64
	Pclntable, Pclntablelen, Pclntablecap       uint64
	Ftab, Ftablen, Ftabcap                      uint64
	Findfunctab                                 uint64
	Minpc                                       uint64
	Maxpc                                       uint64
	Text                                        uint64
	Etext                                       uint64
	Noptrdata                                   uint64
	Enoptrdata                                  uint64
	Data                                        uint64
	Edata                                       uint64
	Bss                                         uint64
	Ebss                                        uint64
	Noptrbss                                    uint64
	Enoptrbss                                   uint64
	End                                         uint64
	Gcdata                                      uint64
	Gcbss                                       uint64
	Types                                       uint64
	Etypes                                      uint64
	Rodata                                      uint64
	Gofunc                                      uint64
	Textsectmap, Textsectmaplen, Textsectmapcap uint64
	Typelinks, Typelinkslen, Typelinkscap       uint64
	Itablinks, Itablinkslen, Itablinkscap       uint64
}

func (md moduledata1864) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypesAddr:     md.Types,
		TypesLen:      md.Etypes - md.Types,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		ITabLinkAddr:  md.Itablinks,
		ITabLinkLen:   md.Itablinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
		GoFuncVal:     md.Gofunc,
	}
}

type moduledata1832 struct {
	PcHeader                                    uint32
	Funcnametab, Funcnametablen, Funcnametabcap uint32
	Cutab, Cutablen, Cutabcap                   uint32
	Filetab, Filetablen, Filetabcap             uint32
	Pctab, Pctablen, Pctabcap                   uint32
	Pclntable, Pclntablelen, Pclntablecap       uint32
	Ftab, Ftablen, Ftabcap                      uint32
	Findfunctab                                 uint32
	Minpc                                       uint32
	Maxpc                                       uint32
	Text                                        uint32
	Etext                                       uint32
	Noptrdata                                   uint32
	Enoptrdata                                  uint32
	Data                                        uint32
	Edata                                       uint32
	Bss                                         uint32
	Ebss                                        uint32
	Noptrbss                                    uint32
	Enoptrbss                                   uint32
	End                                         uint32
	Gcdata                                      uint32
	Gcbss                                       uint32
	Types                                       uint32
	Etypes                                      uint32
	Rodata                                      uint32
	Gofunc                                      uint32
	Textsectmap, Textsectmaplen, Textsectmapcap uint32
	Typelinks, Typelinkslen, Typelinkscap       uint32
	Itablinks, Itablinkslen, Itablinkscap       uint32
}

func (md moduledata1832) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypesAddr:     uint64(md.Types),
		TypesLen:      uint64(md.Etypes - md.Types),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		ITabLinkAddr:  uint64(md.Itablinks),
		ITabLinkLen:   uint64(md.Itablinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
		GoFuncVal:     uint64(md.Gofunc),
	}
}

type moduledata1664 struct {
	PcHeader                                    uint64
	Funcnametab, Funcnametablen, Funcnametabcap uint64
	Cutab, Cutablen, Cutabcap                   uint64
	Filetab, Filetablen, Filetabcap             uint64
	Pctab, Pctablen, Pctabcap                   uint64
	Pclntable, Pclntablelen, Pclntablecap       uint64
	Ftab, Ftablen, Ftabcap                      uint64
	Findfunctab                                 uint64
	Minpc                                       uint64
	Maxpc                                       uint64
	Text                                        uint64
	Etext                                       uint64
	Noptrdata                                   uint64
	Enoptrdata                                  uint64
	Data                                        uint64
	Edata                                       uint64
	Bss                                         uint64
	Ebss                                        uint64
	Noptrbss                                    uint64
	Enoptrbss                                   uint64
	End                                         uint64
	Gcdata                                      uint64
	Gcbss                                       uint64
	Types                                       uint64
	Etypes                                      uint64
	Textsectmap, Textsectmaplen, Textsectmapcap uint64
	Typelinks, Typelinkslen, Typelinkscap       uint64
	Itablinks, Itablinkslen, Itablinkscap       uint64
}

func (md moduledata1664) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypesAddr:     md.Types,
		TypesLen:      md.Etypes - md.Types,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		ITabLinkAddr:  md.Itablinks,
		ITabLinkLen:   md.Itablinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
	}
}

type moduledata1632 struct {
	PcHeader                                    uint32
	Funcnametab, Funcnametablen, Funcnametabcap uint32
	Cutab, Cutablen, Cutabcap                   uint32
	Filetab, Filetablen, Filetabcap             uint32
	Pctab, Pctablen, Pctabcap                   uint32
	Pclntable, Pclntablelen, Pclntablecap       uint32
	Ftab, Ftablen, Ftabcap                      uint32
	Findfunctab                                 uint32
	Minpc                                       uint32
	Maxpc                                       uint32
	Text                                        uint32
	Etext                                       uint32
	Noptrdata                                   uint32
	Enoptrdata                                  uint32
	Data                                        uint32
	Edata                                       uint32
	Bss                                         uint32
	Ebss                                        uint32
	Noptrbss                                    uint32
	Enoptrbss                                   uint32
	End                                         uint32
	Gcdata                                      uint32
	Gcbss                                       uint32
	Types                                       uint32
	Etypes                                      uint32
	Textsectmap, Textsectmaplen, Textsectmapcap uint32
	Typelinks, Typelinkslen, Typelinkscap       uint32
	Itablinks, Itablinkslen, Itablinkscap       uint32
}

func (md moduledata1632) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypesAddr:     uint64(md.Types),
		TypesLen:      uint64(md.Etypes - md.Types),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		ITabLinkAddr:  uint64(md.Itablinks),
		ITabLinkLen:   uint64(md.Itablinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
	}
}

type moduledata864 struct {
	Pclntable, Pclntablelen, Pclntablecap       uint64
	Ftab, Ftablen, Ftabcap                      uint64
	Filetab, Filetablen, Filetabcap             uint64
	Findfunctab                                 uint64
	Minpc                                       uint64
	Maxpc                                       uint64
	Text                                        uint64
	Etext                                       uint64
	Noptrdata                                   uint64
	Enoptrdata                                  uint64
	Data                                        uint64
	Edata                                       uint64
	Bss                                         uint64
	Ebss                                        uint64
	Noptrbss                                    uint64
	Enoptrbss                                   uint64
	End                                         uint64
	Gcdata                                      uint64
	Gcbss                                       uint64
	Types                                       uint64
	Etypes                                      uint64
	Textsectmap, Textsectmaplen, Textsectmapcap uint64
	Typelinks, Typelinkslen, Typelinkscap       uint64
	Itablinks, Itablinkslen, Itablinkscap       uint64
}

func (md moduledata864) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypesAddr:     md.Types,
		TypesLen:      md.Etypes - md.Types,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		ITabLinkAddr:  md.Itablinks,
		ITabLinkLen:   md.Itablinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
	}
}

type moduledata832 struct {
	Pclntable, Pclntablelen, Pclntablecap       uint32
	Ftab, Ftablen, Ftabcap                      uint32
	Filetab, Filetablen, Filetabcap             uint32
	Findfunctab                                 uint32
	Minpc                                       uint32
	Maxpc                                       uint32
	Text                                        uint32
	Etext                                       uint32
	Noptrdata                                   uint32
	Enoptrdata                                  uint32
	Data                                        uint32
	Edata                                       uint32
	Bss                                         uint32
	Ebss                                        uint32
	Noptrbss                                    uint32
	Enoptrbss                                   uint32
	End                                         uint32
	Gcdata                                      uint32
	Gcbss                                       uint32
	Types                                       uint32
	Etypes                                      uint32
	Textsectmap, Textsectmaplen, Textsectmapcap uint32
	Typelinks, Typelinkslen, Typelinkscap       uint32
	Itablinks, Itablinkslen, Itablinkscap       uint32
}

func (md moduledata832) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypesAddr:     uint64(md.Types),
		TypesLen:      uint64(md.Etypes - md.Types),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		ITabLinkAddr:  uint64(md.Itablinks),
		ITabLinkLen:   uint64(md.Itablinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
	}
}

type moduledata764 struct {
	Pclntable, Pclntablelen, Pclntablecap uint64
	Ftab, Ftablen, Ftabcap                uint64
	Filetab, Filetablen, Filetabcap       uint64
	Findfunctab                           uint64
	Minpc                                 uint64
	Maxpc                                 uint64
	Text                                  uint64
	Etext                                 uint64
	Noptrdata                             uint64
	Enoptrdata                            uint64
	Data                                  uint64
	Edata                                 uint64
	Bss                                   uint64
	Ebss                                  uint64
	Noptrbss                              uint64
	Enoptrbss                             uint64
	End                                   uint64
	Gcdata                                uint64
	Gcbss                                 uint64
	Types                                 uint64
	Etypes                                uint64
	Typelinks, Typelinkslen, Typelinkscap uint64
	Itablinks, Itablinkslen, Itablinkscap uint64
}

func (md moduledata764) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypesAddr:     md.Types,
		TypesLen:      md.Etypes - md.Types,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		ITabLinkAddr:  md.Itablinks,
		ITabLinkLen:   md.Itablinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
	}
}

type moduledata732 struct {
	Pclntable, Pclntablelen, Pclntablecap uint32
	Ftab, Ftablen, Ftabcap                uint32
	Filetab, Filetablen, Filetabcap       uint32
	Findfunctab                           uint32
	Minpc                                 uint32
	Maxpc                                 uint32
	Text                                  uint32
	Etext                                 uint32
	Noptrdata                             uint32
	Enoptrdata                            uint32
	Data                                  uint32
	Edata                                 uint32
	Bss                                   uint32
	Ebss                                  uint32
	Noptrbss                              uint32
	Enoptrbss                             uint32
	End                                   uint32
	Gcdata                                uint32
	Gcbss                                 uint32
	Types                                 uint32
	Etypes                                uint32
	Typelinks, Typelinkslen, Typelinkscap uint32
	Itablinks, Itablinkslen, Itablinkscap uint32
}

func (md moduledata732) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypesAddr:     uint64(md.Types),
		TypesLen:      uint64(md.Etypes - md.Types),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		ITabLinkAddr:  uint64(md.Itablinks),
		ITabLinkLen:   uint64(md.Itablinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
	}
}

type moduledata564 struct {
	Pclntable, Pclntablelen, Pclntablecap uint64
	Ftab, Ftablen, Ftabcap                uint64
	Filetab, Filetablen, Filetabcap       uint64
	Findfunctab                           uint64
	Minpc                                 uint64
	Maxpc                                 uint64
	Text                                  uint64
	Etext                                 uint64
	Noptrdata                             uint64
	Enoptrdata                            uint64
	Data                                  uint64
	Edata                                 uint64
	Bss                                   uint64
	Ebss                                  uint64
	Noptrbss                              uint64
	Enoptrbss                             uint64
	End                                   uint64
	Gcdata                                uint64
	Gcbss                                 uint64
	Typelinks, Typelinkslen, Typelinkscap uint64
}

func (md moduledata564) toModuledata() moduledata {
	return moduledata{
		TextAddr:      md.Text,
		TextLen:       md.Etext - md.Text,
		NoPtrDataAddr: md.Noptrdata,
		NoPtrDataLen:  md.Enoptrdata - md.Noptrdata,
		DataAddr:      md.Data,
		DataLen:       md.Edata - md.Data,
		BssAddr:       md.Bss,
		BssLen:        md.Ebss - md.Bss,
		NoPtrBssAddr:  md.Noptrbss,
		NoPtrBssLen:   md.Enoptrbss - md.Noptrbss,
		TypelinkAddr:  md.Typelinks,
		TypelinkLen:   md.Typelinkslen,
		FuncTabAddr:   md.Ftab,
		FuncTabLen:    md.Ftablen,
		PCLNTabAddr:   md.Pclntable,
		PCLNTabLen:    md.Pclntablelen,
	}
}

type moduledata532 struct {
	Pclntable, Pclntablelen, Pclntablecap uint32
	Ftab, Ftablen, Ftabcap                uint32
	Filetab, Filetablen, Filetabcap       uint32
	Findfunctab                           uint32
	Minpc                                 uint32
	Maxpc                                 uint32
	Text                                  uint32
	Etext                                 uint32
	Noptrdata                             uint32
	Enoptrdata                            uint32
	Data                                  uint32
	Edata                                 uint32
	Bss                                   uint32
	Ebss                                  uint32
	Noptrbss                              uint32
	Enoptrbss                             uint32
	End                                   uint32
	Gcdata                                uint32
	Gcbss                                 uint32
	Typelinks, Typelinkslen, Typelinkscap uint32
}

func (md moduledata532) toModuledata() moduledata {
	return moduledata{
		TextAddr:      uint64(md.Text),
		TextLen:       uint64(md.Etext - md.Text),
		NoPtrDataAddr: uint64(md.Noptrdata),
		NoPtrDataLen:  uint64(md.Enoptrdata - md.Noptrdata),
		DataAddr:      uint64(md.Data),
		DataLen:       uint64(md.Edata - md.Data),
		BssAddr:       uint64(md.Bss),
		BssLen:        uint64(md.Ebss - md.Bss),
		NoPtrBssAddr:  uint64(md.Noptrbss),
		NoPtrBssLen:   uint64(md.Enoptrbss - md.Noptrbss),
		TypelinkAddr:  uint64(md.Typelinks),
		TypelinkLen:   uint64(md.Typelinkslen),
		FuncTabAddr:   uint64(md.Ftab),
		FuncTabLen:    uint64(md.Ftablen),
		PCLNTabAddr:   uint64(md.Pclntable),
		PCLNTabLen:    uint64(md.Pclntablelen),
	}
}
