package gore

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestOsAwarePathDir(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{input: "path/to/file", expected: "path/to"},
		{input: "path/to/dir/", expected: "path/to/dir"},
		{input: "<autogenerated>", expected: "<autogenerated>"},
	}

	for _, test := range tests {
		actual := osAwarePathDir(test.input)
		assert.Equal(t, test.expected, actual)
	}
}

func TestOsAwarePathBase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{input: "path/to/file", expected: "file"},
		{input: "path/to/dir/", expected: "dir"},
		{input: "<autogenerated>", expected: "<autogenerated>"},
	}

	for _, test := range tests {
		actual := osAwarePathBase(test.input)
		assert.Equal(t, test.expected, actual)
	}
}

func TestOsAwarePathClean(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{input: "path/to/file", expected: "path/to/file"},
		{input: "path/to/dir/", expected: "path/to/dir"},
		{input: "<autogenerated>", expected: "<autogenerated>"},
		{input: "path/./to/../file", expected: "path/file"},
	}

	for _, test := range tests {
		actual := osAwarePathClean(test.input)
		assert.Equal(t, test.expected, actual)
	}
}
